version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: dotnet restore
      
      - run:
          name: Create a test build
          command: dotnet build --configuration Release
      
      - run:
          name: Install Playwright browsers
          command: pwsh playwright-nunit/bin/Release/net9.0/playwright.ps1 install
      
      - run:
          name: Run CSharp Playwright tests
          command: dotnet test --configuration Release --no-build --logger "html;LogFileName=index.html"
      
      - store_artifacts:
          path: '**/TestResults'
          destination: playwright-csharp-results

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
